name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get configuration from AWS AppConfig
      id: get_config
      run: |
        app_id=fd164b1
        env_id=43euy98
        config_profile_id=q2oavmr
        
        config=$(aws appconfig get-configuration \
          --application $app_id \
          --environment $env_id \
          --configuration $config_profile_id \
          --client-id client_$(date +%s) \
          --query Content \
          --output text)
        
        echo "$config" > .env
        
        echo "Config retrieved: $config"

    - name: Use .env file
      run: |
        source .env
        echo "MY_ENV_VAR=$MY_ENV_VAR"